package loginFeat;

import java.util.ArrayList;

/**
 * User class to represent a user of the program, defined by his/her username, password and Id
 * @author roman
 * @version 1.0
 * @see Logger
 * @see LogActionListener
 * @see RegisterActionListener
 *
 */
public class User {
	
	/**
	 * Username of the user
	 * @see Logger()
	 * @see LoggerGUI
	 * @see LogActionListener()
	 * @see RegisterActionListener()
	 */
	private String username;
	/**
	 * Password of the user
	 * @see Logger()
	 * @see LoggerGUI
	 * @see LogActionListener()
	 * @see RegisterActionListener()
	 */
	private String password;
	/**
	 * Id of the user, not entered by the user but generated by the program
	 * @see Logger()
	 * @see LoggerGUI
	 * @see LogActionListener()
	 * @see RegisterActionListener()
	 */
	private int id;
	
	/**
	 * List of Contacts attached to the User's account
	 */
	public ArrayList<User> Contacts = new ArrayList<User>();
	
public User(String username, String password, int id) {
		setUsername(username);
		setPassword(password);
		setId(id);
	}
	
	public void setUsername(String username) {
		this.username = username;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getPassword() {
		return password;
	}
	
	public int getId() {
		return id;
	}
	
	public String getUsername() {
		return username;
	}
	
	public ArrayList<User> getContacts(){
		return Contacts;
	}
	
	public void AddContact(ArrayList<User> Contacts, User userToAdd) {
		Contacts.add(userToAdd);
	}
	
	public void removeContact(ArrayList<User> Contacts, User userToRemove) {
		Contacts.remove(userToRemove);
	}
}
